# Generated by Django 5.1.2 on 2024-11-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='equipo_nba',
            new_name='equipo_que_milita',
        ),
        migrations.RenameField(
            model_name='jugador',
            old_name='edad',
            new_name='numero_jugador',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
