# Generated by Django 5.1.2 on 2024-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_rename_equipo_nba_jugador_equipo_que_milita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundacion',
            field=models.DateField(),
        ),
    ]
