# Generated by Django 5.1.2 on 2024-11-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_datosextra_deporte_fav_datosextra_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='deporte_fav',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='equipo_fav',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
