# Generated by Django 5.1.2 on 2024-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_datosextra_deporte_fav_alter_datosextra_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='deporte_fav',
            field=models.CharField(default='basquet', max_length=20),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='edad',
            field=models.IntegerField(default='23'),
        ),
        migrations.AlterField(
            model_name='datosextra',
            name='equipo_fav',
            field=models.CharField(default='Lakers', max_length=20),
        ),
    ]
