# Generated by Django 5.1.2 on 2024-11-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_datosextra_fecha_datosextra_nueva_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
