# Generated by Django 5.1.2 on 2024-11-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_datosextra_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
